/*
 * Copyright 2014 Giulio Camuffo <giuliocamuffo@gmail.com>
 *
 * This file is part of Orbital
 *
 * Orbital is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Orbital is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Orbital.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * This file was originally generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp org.kde.StatusNotifierWatcher.xml -a statusnotifierwatcher -c StatusNotifierWatcher
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 */

#include <QtCore/QStringList>

#include "statusnotifierwatcher.h"

StatusNotifierWatcher::StatusNotifierWatcher(QObject *parent)
                     : QDBusAbstractAdaptor(parent)
{
    setAutoRelaySignals(true);
}

StatusNotifierWatcher::~StatusNotifierWatcher()
{
}

bool StatusNotifierWatcher::isStatusNotifierHostRegistered() const
{
    // we always have an implicit host
    return true;
}

int StatusNotifierWatcher::protocolVersion() const
{
    return 0;
}

QStringList StatusNotifierWatcher::registeredStatusNotifierItems() const
{
    //TODO
    return QStringList();
}

void StatusNotifierWatcher::RegisterStatusNotifierHost(const QString &service)
{
    //TODO
}

void StatusNotifierWatcher::RegisterStatusNotifierItem(const QString &service)
{
    emit newItem(service);
}
