#!/bin/sh

# API Key provided by Alan@imgur.com
apikey="b3625162d3418ac51a9ee805b1840452"
file="$1"

response=$(curl -F "key=$apikey" -H "Expect: " -F "image=@$file" \
        http://imgur.com/api/upload.xml 2>/dev/null)
# the "Expect: " header is to get around a problem when using this through
# the Squid proxy. Not sure if it's a Squid bug or what.
if [ $? -ne 0 ]; then
    echo "Upload failed" >&2
    exit 1
elif [ $(echo $response | grep -c "<error_msg>") -gt 0 ]; then
    echo "Error message from imgur:" >&2
    echo $response | sed -r 's/.*<error_msg>(.*)<\/error_msg>.*/\1/' >&2
    exit 1
fi

# parse the response and output our stuff
url=$(echo $response | sed -r 's/.*<original_image>(.*)<\/original_image>.*/\1/')
deleteurl=$(echo $response | sed -r 's/.*<delete_page>(.*)<\/delete_page>.*/\1/')
printf $url
printf "Delete page: $deleteurl" >&2
